df = read.table("cholesterol.txt",header=T)
plot(df)
modele = lm(y~x,df)
abline(-0.1824,17.9014,col="red")
summary(modele)
anova(modele)
modele2 = lm(y~x-1,df)
summary(modele2)
anova(modele2)
F=(anova(modele2)$"Sum Sq"[2]-anova(modele)$"Sum Sq"[2])/(anova(modele)$"Sum Sq"[2]/16)
1-pf(3.37,1,16)
anova(modele2,modele)
